services:
  sadnd.server:
    image: ${DOCKER_REGISTRY-}sadndserver
    container_name: SADnD.api
    build:
      context: .
      dockerfile: SADnD/Server/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - sadnd.database

  sadnd.database:
    image: postgres:latest
    container_name: SADnD.database
    environment:
      - POSTGRES_DB=sadnd
      - POSTGRES_USER=sadnd
      - POSTGRES_PASSWORD=sadnd
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  sadnd.nginx:
    image: nginx:latest
    container_name: SADnD.nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/cerbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - sadnd.server

  sadnd.certbot:
    image: certbot/certbot
    container_name: SADnD.certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot