services:
  sadnd.server:
    image: ${DOCKER_REGISTRY-}sadndserver
    container_name: SADnD.server
    restart: unless-stopped
    build:
      context: .
      dockerfile: SADnD/Server/Dockerfile
    user: root
    environment:
      - ASPNETCORE_URLS=http://+80
    ports:
      - 5000:80
    depends_on:
      - sadnd.database

  sadnd.database:
    image: postgres:latest
    container_name: SADnD.database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=sadnd
      - POSTGRES_USER=sadnd
      - POSTGRES_PASSWORD=sadnd
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432