name: Deploy and Restart Containers

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop and remove old Version
        uses: appleboy/ssh-action@v1.1.0
        with: 
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          script: |
            cd /share/Container/SADnD
            echo ${{ secrets.PASS }} | sudo -S ./cleanup.sh

      - name: Copy files to server
        env:
          ROOT_PATH: /share/Container/SADnD/
        uses: appleboy/scp-action@v0.1.7
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          source: "./"
          target: "/share/Container/SADnD/"

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.1.0
        with: 
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          script: |
            cd /share/Container/SADnD
            echo ${{ secrets.PASS }} | sudo -S ./buildRestart.sh
