name: Deploy and Restart Containers

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Compress project
        run: tar -czf project.tar.gz . --exclude=project.tar.gz

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          source: "project.tar.gz"
          target: "/share/Container/SADnD/"

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.1.0
        with: 
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd /share/Container/SADnD
            tar -xzf project.tar.gz
            rm project.tar.gz
            docker compose down
            docker compose up -d --build